version: "3.9"

services:
  mcp-api:
    container_name: mcp-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - ENV=production
    restart: always
    volumes:
      - .:/app
